/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_DedicatedNAS_Message_H_
#define	_DedicatedNAS_Message_H_

#include "typdef.h"

/* DedicatedNAS-Message */
typedef OCTET_STRING_t DedicatedNAS_Message_t;
     
#endif