/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_EstablishmentCause_H_
#define	_EstablishmentCause_H_

#include "typdef.h"
/* Dependencies */
typedef enum EstablishmentCause {
	EstablishmentCause_emergency	= 0,
	EstablishmentCause_highPriorityAccess	= 1,
	EstablishmentCause_mt_Access	= 2,
	EstablishmentCause_mo_Signalling	= 3,
	EstablishmentCause_mo_Data	= 4,
	EstablishmentCause_mo_VoiceCall	= 5,
	EstablishmentCause_mo_VideoCall	= 6,
	EstablishmentCause_mo_SMS	= 7,
	EstablishmentCause_mps_PriorityAccess	= 8,
	EstablishmentCause_mcs_PriorityAccess	= 9,
	EstablishmentCause_spare6	= 10,
	EstablishmentCause_spare5	= 11,
	EstablishmentCause_spare4	= 12,
	EstablishmentCause_spare3	= 13,
	EstablishmentCause_spare2	= 14,
	EstablishmentCause_spare1	= 15
} e_EstablishmentCause;

/* EstablishmentCause */
typedef uint16_t EstablishmentCause_t;

#endif	/* _EstablishmentCause_H_ */

