/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RadioBearerConfig_H_
#define	_RadioBearerConfig_H_

/* RadioBearerConfig */
typedef struct RadioBearerConfig {
    asn_struct_ctx_t _asn_ctx;
} RadioBearerConfig_t;

#endif	/* _RadioBearerConfig_H_ */
