/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RegisteredAMF_H_
#define	_RegisteredAMF_H_

#include "AMF-Identifier.h"
#include "PLMN-Identity.h"

/* RegisteredAMF */
typedef struct RegisteredAMF {
	PLMN_Identity_t	*plmn_Identity	/* OPTIONAL */;
	AMF_Identifier_t	 amf_Identifier;

} RegisteredAMF_t;

#endif	/* _RegisteredAMF_H_ */

