/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRC_TransactionIdentifier_H_
#define	_RRC_TransactionIdentifier_H_


/* RRC-TransactionIdentifier */
typedef long RRC_TransactionIdentifier_t;

#endif	/* _RRC_TransactionIdentifier_H_ */

