/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetupRequest_IEs_H_
#define	_RRCSetupRequest_IEs_H_

#include "EstablishmentCause.h"
#include "typdef.h"
#include "InitialUE-Identity.h"

/* RRCSetupRequest-IEs */
typedef struct RRCSetupRequest_IEs {
	InitialUE_Identity_t	 ue_Identity;
	EstablishmentCause_t	 establishmentCause;
	//BIT_STRING_t spare;
	asn_struct_ctx_t _asn_ctx;
} RRCSetupRequest_IEs_t;

#endif	/* _RRCSetupRequest_IEs_H_ */
