/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetupComplete_v1610_IEs_H_
#define	_RRCSetupComplete_v1610_IEs_H_

/* Dependencies */
typedef enum RRCSetupComplete_v1610_IEs__iab_NodeIndication_r16 {
	RRCSetupComplete_v1610_IEs__iab_NodeIndication_r16_true	= 0
} e_RRCSetupComplete_v1610_IEs__iab_NodeIndication_r16;
typedef enum RRCSetupComplete_v1610_IEs__idleMeasAvailable_r16 {
	RRCSetupComplete_v1610_IEs__idleMeasAvailable_r16_true	= 0
} e_RRCSetupComplete_v1610_IEs__idleMeasAvailable_r16;
typedef enum RRCSetupComplete_v1610_IEs__mobilityHistoryAvail_r16 {
	RRCSetupComplete_v1610_IEs__mobilityHistoryAvail_r16_true	= 0
} e_RRCSetupComplete_v1610_IEs__mobilityHistoryAvail_r16;
typedef enum RRCSetupComplete_v1610_IEs__mobilityState_r16 {
	RRCSetupComplete_v1610_IEs__mobilityState_r16_normal	= 0,
	RRCSetupComplete_v1610_IEs__mobilityState_r16_medium	= 1,
	RRCSetupComplete_v1610_IEs__mobilityState_r16_high	= 2,
	RRCSetupComplete_v1610_IEs__mobilityState_r16_spare	= 3
} e_RRCSetupComplete_v1610_IEs__mobilityState_r16;

/* Forward declarations */
struct UE_MeasurementsAvailable_r16;
struct RRCSetupComplete_v1690_IEs;

/* RRCSetupComplete-v1610-IEs */
typedef struct RRCSetupComplete_v1610_IEs {
	long	*iab_NodeIndication_r16	/* OPTIONAL */;
	long	*idleMeasAvailable_r16	/* OPTIONAL */;
	struct UE_MeasurementsAvailable_r16	*ue_MeasurementsAvailable_r16	/* OPTIONAL */;
	long	*mobilityHistoryAvail_r16	/* OPTIONAL */;
	long	*mobilityState_r16	/* OPTIONAL */;
	struct RRCSetupComplete_v1690_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
} RRCSetupComplete_v1610_IEs_t;

#endif	/* _RRCSetupComplete_v1610_IEs_H_ */
