/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetupRequest_H_
#define	_RRCSetupRequest_H_

#include "RRCSetupRequest-IEs.h"

/* RRCSetupRequest */
typedef struct RRCSetupRequest {
	RRCSetupRequest_IEs_t	 rrcSetupRequest;
	
} RRCSetupRequest_t;



#endif	/* _RRCSetupRequest_H_ */
