/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetupComplete_v1690_IEs_H_
#define	_RRCSetupComplete_v1690_IEs_H_

/* Dependencies */
typedef enum RRCSetupComplete_v1690_IEs__ul_RRC_Segmentation_r16 {
	RRCSetupComplete_v1690_IEs__ul_RRC_Segmentation_r16_true	= 0
} e_RRCSetupComplete_v1690_IEs__ul_RRC_Segmentation_r16;

/* Forward declarations */
struct RRCSetupComplete_v1700_IEs;

/* RRCSetupComplete-v1690-IEs */
typedef struct RRCSetupComplete_v1690_IEs {
	long	*ul_RRC_Segmentation_r16	/* OPTIONAL */;
	struct RRCSetupComplete_v1700_IEs	*nonCriticalExtension	/* OPTIONAL */;

} RRCSetupComplete_v1690_IEs_t;


#endif	/* _RRCSetupComplete_v1690_IEs_H_ */

