/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_S_NSSAI_H_
#define	_S_NSSAI_H_
#include "typdef.h"
/* Dependencies */
typedef enum S_NSSAI_PR {
	S_NSSAI_PR_NOTHING,	/* No components present */
	S_NSSAI_PR_sst,
	S_NSSAI_PR_sst_SD
} S_NSSAI_PR;

/* S-NSSAI */
typedef struct S_NSSAI {
	S_NSSAI_PR present;
	union S_NSSAI_u {
		BIT_STRING_t	 sst;
		BIT_STRING_t	 sst_SD;
	} choice;
	
} S_NSSAI_t;


#endif	/* _S_NSSAI_H_ */
