/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_SL_L2RemoteUE_Config_r17_H_
#define	_SL_L2RemoteUE_Config_r17_H_


/* SL-L2RemoteUE-Config-r17 */
typedef struct SL_L2RemoteUE_Config_r17 {
	int:0;
	//todo

} SL_L2RemoteUE_Config_r17_t;

#endif	/* _SL_L2RemoteUE_Config_r17_H_ */
