/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_AMF_Identifier_H_
#define	_AMF_Identifier_H_

#include "typdef.h"

/* AMF-Identifier */
typedef BIT_STRING_t AMF_Identifier_t;

#endif	/* _AMF_Identifier_H_ */

