/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_NG_5G_S_TMSI_H_
#define	_NG_5G_S_TMSI_H_

#include "typdef.h"

/* NG-5G-S-TMSI */
typedef BIT_STRING_t NG_5G_S_TMSI_t;

#endif	/* _NG_5G_S_TMSI_H_ */
