/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_PLMN_Identity_H_
#define	_PLMN_Identity_H_

#include "asn_struct.h"

/* PLMN-Identity */
typedef struct PLMN_Identity_s {
	asn_struct_ctx_t _asn_ctx;
} PLMN_Identity_t;


#endif	/* _PLMN_Identity_H_ */
