/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RejectWaitTime_H_
#define	_RejectWaitTime_H_

/* RejectWaitTime */
typedef long	 RejectWaitTime_t;

#endif	/* _RejectWaitTime_H_ */
