/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCReject_H_
#define	_RRCReject_H_

#include "RRCReject-IEs.h"

/* Dependencies */
typedef enum RRCReject__criticalExtensions_PR {
	RRCReject__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCReject__criticalExtensions_PR_rrcReject,
	RRCReject__criticalExtensions_PR_criticalExtensionsFuture
} RRCReject__criticalExtensions_PR;

/* RRCReject */
typedef struct RRCReject {
	struct RRCReject__criticalExtensions {
		RRCReject__criticalExtensions_PR present;
		union RRCReject__criticalExtensions_u {
			RRCReject_IEs_t	 rrcReject;
			struct RRCReject__criticalExtensions__criticalExtensionsFuture {
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensionsFuture;
		} choice;
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
asn_struct_ctx_t _asn_ctx;
} RRCReject_t;


#endif	/* _RRCReject_H_ */
