/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetupComplete_H_
#define	_RRCSetupComplete_H_

#include "RRC-TransactionIdentifier.h"
#include "RRCSetupComplete-IEs.h"

/* Dependencies */
typedef enum RRCSetupComplete__criticalExtensions_PR {
	RRCSetupComplete__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCSetupComplete__criticalExtensions_PR_rrcSetupComplete,
	RRCSetupComplete__criticalExtensions_PR_criticalExtensionsFuture
} RRCSetupComplete__criticalExtensions_PR;

/* RRCSetupComplete */
typedef struct RRCSetupComplete {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	struct RRCSetupComplete__criticalExtensions {
		RRCSetupComplete__criticalExtensions_PR present;
		union RRCSetupComplete__criticalExtensions_u {
			RRCSetupComplete_IEs_t	 rrcSetupComplete;
			struct RRCSetupComplete__criticalExtensions__criticalExtensionsFuture {
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensionsFuture;
		} choice;
	asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	asn_struct_ctx_t _asn_ctx;
} RRCSetupComplete_t;


#endif	/* _RRCSetupComplete_H_ */
