/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetup_IEs_H_
#define	_RRCSetup_IEs_H_


/* Forward declarations */
#include "RadioBearerConfig.h"
#include "typdef.h"
#include "RRCSetup-v1700-IEs.h"

/* RRCSetup-IEs */
typedef struct RRCSetup_IEs {
	RadioBearerConfig_t	 radioBearerConfig;
	OCTET_STRING_t	 masterCellGroup;
	OCTET_STRING_t	*lateNonCriticalExtension	/* OPTIONAL */;
	struct RRCSetup_v1700_IEs	*nonCriticalExtension	/* OPTIONAL */;

} RRCSetup_IEs_t;


#endif	/* _RRCSetup_IEs_H_ */
