/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetupComplete_IEs_H_
#define	_RRCSetupComplete_IEs_H_

#include "typdef.h"
/* Dependencies */
typedef enum RRCSetupComplete_IEs__guami_Type {
	RRCSetupComplete_IEs__guami_Type_native	= 0,
	RRCSetupComplete_IEs__guami_Type_mapped	= 1
} e_RRCSetupComplete_IEs__guami_Type;
typedef enum RRCSetupComplete_IEs__ng_5G_S_TMSI_Value_PR {
	RRCSetupComplete_IEs__ng_5G_S_TMSI_Value_PR_NOTHING,	/* No components present */
	RRCSetupComplete_IEs__ng_5G_S_TMSI_Value_PR_ng_5G_S_TMSI,
	RRCSetupComplete_IEs__ng_5G_S_TMSI_Value_PR_ng_5G_S_TMSI_Part2
} RRCSetupComplete_IEs__ng_5G_S_TMSI_Value_PR;

/* Forward declarations */
struct RegisteredAMF;
struct RRCSetupComplete_v1610_IEs;
#include "S-NSSAI.h"
#include "DedicatedNAS-Message.h"
#include "NG-5G-S-TMSI.h"

/* RRCSetupComplete-IEs */
typedef struct RRCSetupComplete_IEs {
	long	 selectedPLMN_Identity;
	struct RegisteredAMF	*registeredAMF	/* OPTIONAL */;
	long	*guami_Type	/* OPTIONAL */;
	struct RRCSetupComplete_IEs__s_NSSAI_List {
		A_SEQUENCE_OF(struct S_NSSAI) list;
		
		
	} *s_NSSAI_List;
	DedicatedNAS_Message_t	 dedicatedNAS_Message;
	struct RRCSetupComplete_IEs__ng_5G_S_TMSI_Value {
		RRCSetupComplete_IEs__ng_5G_S_TMSI_Value_PR present;
		union RRCSetupComplete_IEs__ng_5G_S_TMSI_Value_u {
			NG_5G_S_TMSI_t	 ng_5G_S_TMSI;
			BIT_STRING_t	 ng_5G_S_TMSI_Part2;
		} choice;
		
	} *ng_5G_S_TMSI_Value;
	OCTET_STRING_t	*lateNonCriticalExtension	/* OPTIONAL */;
	struct RRCSetupComplete_v1610_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
} RRCSetupComplete_IEs_t;

#endif	/* _RRCSetupComplete_IEs_H_ */
