/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetupComplete_v1800_IEs_H_
#define	_RRCSetupComplete_v1800_IEs_H_
#include "asn_struct.h"
/* Dependencies */
typedef enum RRCSetupComplete_v1800_IEs__ncr_NodeIndication_r18 {
	RRCSetupComplete_v1800_IEs__ncr_NodeIndication_r18_true	= 0
} e_RRCSetupComplete_v1800_IEs__ncr_NodeIndication_r18;
typedef enum RRCSetupComplete_v1800_IEs__musim_CapRestrictionInd_r18 {
	RRCSetupComplete_v1800_IEs__musim_CapRestrictionInd_r18_true	= 0
} e_RRCSetupComplete_v1800_IEs__musim_CapRestrictionInd_r18;
typedef enum RRCSetupComplete_v1800_IEs__flightPathInfoAvailable_r18 {
	RRCSetupComplete_v1800_IEs__flightPathInfoAvailable_r18_true	= 0
} e_RRCSetupComplete_v1800_IEs__flightPathInfoAvailable_r18;
typedef enum RRCSetupComplete_v1800_IEs__measConfigReportAppLayerAvailable_r18 {
	RRCSetupComplete_v1800_IEs__measConfigReportAppLayerAvailable_r18_true	= 0
} e_RRCSetupComplete_v1800_IEs__measConfigReportAppLayerAvailable_r18;
typedef enum RRCSetupComplete_v1800_IEs__mobileIAB_NodeIndication_r18 {
	RRCSetupComplete_v1800_IEs__mobileIAB_NodeIndication_r18_true	= 0
} e_RRCSetupComplete_v1800_IEs__mobileIAB_NodeIndication_r18;
typedef enum RRCSetupComplete_v1800_IEs__reselectionMeasAvailable_r18 {
	RRCSetupComplete_v1800_IEs__reselectionMeasAvailable_r18_true	= 0
} e_RRCSetupComplete_v1800_IEs__reselectionMeasAvailable_r18;

/* RRCSetupComplete-v1800-IEs */
typedef struct RRCSetupComplete_v1800_IEs {
	long	*ncr_NodeIndication_r18	/* OPTIONAL */;
	long	*musim_CapRestrictionInd_r18	/* OPTIONAL */;
	long	*flightPathInfoAvailable_r18	/* OPTIONAL */;
	long	*measConfigReportAppLayerAvailable_r18	/* OPTIONAL */;
	long	*mobileIAB_NodeIndication_r18	/* OPTIONAL */;
	long	*reselectionMeasAvailable_r18	/* OPTIONAL */;
	struct RRCSetupComplete_v1800_IEs__nonCriticalExtension {
			asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	asn_struct_ctx_t _asn_ctx;
} RRCSetupComplete_v1800_IEs_t;

#endif	/* _RRCSetupComplete_v1800_IEs_H_ */
