/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetupComplete_v1700_IEs_H_
#define	_RRCSetupComplete_v1700_IEs_H_

/* Dependencies */
typedef enum RRCSetupComplete_v1700_IEs__onboardingRequest_r17 {
	RRCSetupComplete_v1700_IEs__onboardingRequest_r17_true	= 0
} e_RRCSetupComplete_v1700_IEs__onboardingRequest_r17;

/* Forward declarations */
struct RRCSetupComplete_v1800_IEs;

/* RRCSetupComplete-v1700-IEs */
typedef struct RRCSetupComplete_v1700_IEs {
	long	*onboardingRequest_r17	/* OPTIONAL */;
	struct RRCSetupComplete_v1800_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
} RRCSetupComplete_v1700_IEs_t;

#endif	/* _RRCSetupComplete_v1700_IEs_H_ */
