/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_SL_ConfigDedicatedNR_r16_H_
#define	_SL_ConfigDedicatedNR_r16_H_


/* SL-ConfigDedicatedNR-r16 */
typedef struct SL_ConfigDedicatedNR_r16 {
	
	asn_struct_ctx_t _asn_ctx;
	//todo
	
} SL_ConfigDedicatedNR_r16_t;


#endif	/* _SL_ConfigDedicatedNR_r16_H_ */
