/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_UE_MeasurementsAvailable_r16_H_
#define	_UE_MeasurementsAvailable_r16_H_
#include "asn_struct.h"
/* UE-MeasurementsAvailable-r16 */
typedef struct UE_MeasurementsAvailable_r16 {
	asn_struct_ctx_t _asn_ctx;
	//todo
} UE_MeasurementsAvailable_r16_t;

#endif	/* _UE_MeasurementsAvailable_r16_H_ */

